锘\xBF//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a 茅t茅 g茅n茅r茅 par un outil.
//     Version du runtime :4.0.30319.488
//
//     Les modifications apport茅es 脿 ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est r茅g茅n茅r茅.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("http://github.com/odeheurles/Disruptor-net/network")]
[assembly: AssemblyProduct("Disruptor")]
[assembly: AssemblyCopyright("Copyright 漏 disruptor-net")]
[assembly: AssemblyVersion("2.10.0")]
[assembly: AssemblyFileVersion("2.10.0")]
